{"error":{"name":"APIError","stack":"APIError\n    at Function.fromError (/Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/node_modules/@coinbase/coinbase-sdk/dist/coinbase/api_error.js:37:26)\n    at /Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/node_modules/@coinbase/coinbase-sdk/dist/coinbase/utils.js:37:52\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Axios.request (/Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/node_modules/axios/lib/core/Axios.js:40:14)\n    at async Function.create (/Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/node_modules/@coinbase/coinbase-sdk/dist/coinbase/wallet.js:147:24)\n    at async WalletService.initialize (/Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/src/services/wallet.ts:33:23)\n    at async TradingAgent.initialize (/Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/src/agent.ts:23:5)\n    at async main (/Users/madhurgupta/Desktop/repos/personal/memecoin-maverick/agent/src/main.ts:30:24)"},"level":"error","message":"Critical error:","timestamp":"2024-12-01T15:19:37.257Z"}
